package com.bikemanager.domain.model

/**
 * Represents a motorcycle in the application.
 *
 * @property id Unique identifier (auto-generated by database)
 * @property name Display name of the bike
 * @property countingMethod Method used to track maintenance (KM or HOURS)
 * @property firebaseRef Firebase reference for cloud sync (null if not synced)
 */
data class Bike(
    val id: Long = 0,
    val name: String,
    val countingMethod: CountingMethod = CountingMethod.KM,
    val firebaseRef: String? = null
)
